name: 'example'
version: 0.0.1

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  web_components: ^0.12.0
  polymer: "^1.0.0-rc.18"
  polyce:
    path: /Users/lejard_h/dev/polyce
  polymer_elements: '^1.0.0-rc.9'
  dart_to_js_script_rewriter: "^0.1.0+4"
  autonotify_observe: "^1.0.0+7"

transformers:
  - autonotify_observe
  - polymer:
      entry_points: web/index.html
  - $dart2js:
      minify: true
      commandLineOptions: ['--trust-type-annotations', '--trust-primitives', '--enable-experimental-mirrors']
  - dart_to_js_script_rewriter

dev_dependencies:
  grinder: any
  yaml: "^2.1.9"
