name: polyce
description: Generation and management of polymer application
version: 0.1.1
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/walletek/polymer_app

executables:
  polyce: polyce

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  analyzer: "^0.27.0"
  polymer: "^1.0.0-rc.14"
  polymer_app_router: "^0.2.0"
  web_components: "^0.12.0"
  reflectable: "^0.5.0"
  dart_to_js_script_rewriter: "^0.1.0+4"
  autonotify_observe: "^1.0.0+7"
  args: "^0.13.4"
  path: "^1.3.9"
  http: "^0.11.3+3"
  dart_style: "^0.2.2"
  serializer: "^0.1.0"

transformers:
  - autonotify_observe
  - polymer:
      entry_points:
      - example/index.html
  - reflectable:
      entry_points:
      - example/index.dart
  - $dart2js:
      minify: true
      commandLineOptions: ['--trust-type-annotations', '--trust-primitives', '--enable-experimental-mirrors']
  - dart_to_js_script_rewriter

dev_dependencies:
  test: '>=0.12.0'