name: polyce
description: Generation and management of polymer application
version: 0.2.0
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: http://polyce.github.io/

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  polymer: "^1.0.0-rc.18"
  polymer_elements: "^1.0.0-rc.9"
  dart_to_js_script_rewriter: "^0.1.0+4"
  autonotify_observe: "^1.0.0+7"
  web_components: ^0.12.0
  browser: ^0.10.0

transformers:
  - autonotify_observe
  - polymer:
      entry_points: example/index.html
  - $dart2js:
      minify: true
      commandLineOptions:
        - --trust-type-annotations
        - --trust-primitives
  - dart_to_js_script_rewriter

dev_dependencies:
  test: '>=0.12.0'
