name: __projectName__
version: 0.0.1

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  polymer: "^1.0.0-rc.14"
  polyce:
    path: ../../
  polymer_elements: '^1.0.0-rc.7'
  dart_to_js_script_rewriter: "^0.1.0+4"
  autonotify_observe: "^1.0.0+7"
  dogma_codegen: '^0.0.2'

transformers:
  - autonotify_observe
  - polymer:
      entry_points: web/index.html
  - $dart2js:
      $include: '**/*.bootstrap.initialize.dart'
      minify: true
      commandLineOptions: ['--trust-type-annotations', '--trust-primitives', '--enable-experimental-mirrors']
  - dart_to_js_script_rewriter

dev_dependencies:
  grinder: any
  yaml: "^2.1.9"
